//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Planets.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DISPLAY_CONTROL             101
#define IDR_MAINFRAME                   128
#define IDR_PLANETTYPE                  129
#define IDD_TIME_LOCATION               130
#define IDD_DATA_DISPLAY                131
#define IDS_JANUARY                     131
#define IDD_RADIUS_DISPLAY              132
#define IDS_FEBRUARY                    132
#define IDD_ASTRONOMICAL_DATA           133
#define IDS_MARCH                       133
#define IDS_APRIL                       134
#define IDD_EQUINOXSOLSTICE             135
#define IDS_MAY                         136
#define IDS_JUNE                        137
#define IDS_JULY                        138
#define IDD_ALMANAC                     139
#define IDD_OPTIONS                     140
#define IDS_AUGUST                      140
#define IDD_ANGULAR_SEPARATION          141
#define IDS_SEPTEMBER                   141
#define IDD_HOR                         142
#define IDS_OCTOBER                     142
#define IDD_RISE_TRANSIT_SET            143
#define IDS_NOVEMBER                    143
#define IDS_DECEMBER                    144
#define IDD_STAR_BOX                    145
#define IDS_SUN                         145
#define IDS_MOON                        146
#define IDD_VARIATION_BOX               146
#define IDS_MERCURY                     147
#define IDD_MOON_PHASES                 147
#define IDS_VENUS                       148
#define IDD_ERROR                       148
#define IDS_EARTH                       149
#define IDS_MARS                        150
#define IDS_JUPITER                     151
#define IDS_SATURN                      152
#define IDS_URANUS                      153
#define IDS_NEPTUNE                     154
#define IDS_PLUTO                       155
#define IDS_RADIAN                      156
#define IDS_DECIMAL                     157
#define IDS_DEGREE                      158
#define IDS_HOUR                        159
#define IDS_NEVER_UP                    160
#define IDS_ALWAYS_UP                   161
#define IDS_NEXT_DAY                    162
#define IDS_AZIMUTH_ALTITUDE            163
#define IDS_EQUATORIAL_APPARENT         164
#define IDS_ECLIPTIC_APPARENT_SPHERICAL 165
#define IDS_ECLIPTIC_TRUE_SPHERICAL     166
#define IDS_ECLIPTIC_TRUE_CARTESIAN     167
#define IDS_HELIOCENTRIC_SPHERICAL      168
#define IDS_HELIOCENTRIC_CARTESIAN      169
#define IDS_RISE_TRANSIT_SET            170
#define IDS_GHA_DEC                     171
#define IDS_ANGULAR_SEPARATION          172
#define IDS_ASC_NODE                    173
#define IDS_ARIES                       174
#define IDS_TAURUS                      175
#define IDS_GEMINI                      176
#define IDS_CANCER                      177
#define IDS_LEO                         178
#define IDS_VIRGO                       179
#define IDS_LIBRA                       180
#define IDS_SCORPIO                     181
#define IDS_SAGITTARIUS                 182
#define IDS_CAPRICORN                   183
#define IDS_AQUARIUS                    184
#define IDS_PISCES                      185
#define IDS_SUN_LONGITUDE               186
#define IDS_MAGNITUDE_ONLY              187
#define IDS_CONSTELLATION_ONLY          188
#define IDS_MAGNITUDE_AND_CONSTELLATION 189
#define IDS_CANCEL                      190
#define IDS_CONSTARS                    191
#define IDS_NONCONSTARS                 192
#define IDS_HELP_URL_NOT_FOUND          193
#define IDS_FONT_SIZE                   194
#define IDS_FONT_8                      195
#define IDS_FONT_10                     196
#define IDS_FONT_12                     197
#define IDS_FONT_14                     198
#define IDS_DEFAULT_FONT                199
#define IDS_FONT_16                     200
#define IDS_FONT_6                      201
#define IDS_FONT_18                     202
#define IDS_FONT_20                     203
#define IDS_FONT_22                     204
#define IDS_EDIT_BOX_DOUBLE             205
#define IDS_EDIT_BOX_INT                206
#define IDS_EDIT_BOX_LATLON             207
#define IDS_LATITUDE                    208
#define IDS_LONGITUDE                   209
#define IDC_YEAR                        1000
#define IDC_MONTH                       1001
#define IDC_DATE                        1002
#define IDC_HOUR                        1003
#define IDC_LATITUDE                    1004
#define IDC_LATITUDE_NS                 1005
#define IDC_LONGITUDE                   1006
#define IDC_LONGITUDE_WE                1007
#define IDC_AMPM                        1008
#define IDC_DAYLIGHT_ST                 1009
#define IDC_PLANET_POSITIONS            1010
#define IDC_JUPITER_ALTITUDE            1011
#define IDC_SATURN_AZIMUTH              1012
#define IDC_SATURN_ALTITUDE             1013
#define IDC_URANUS_AZIMUTH              1014
#define IDC_URANUS_ALTITUDE             1015
#define IDC_NEPTUNE_AZIMUTH             1016
#define IDC_NEPTUNE_ALTITUDE            1017
#define IDC_PLUTO_AZIMUTH               1018
#define IDC_PLUTO_ALTITUDE              1019
#define IDC_MERCURY_RADIUS              1020
#define IDC_TIME_ZONE                   1021
#define IDC_DATA_TITLE                  1022
#define IDC_MARS_RADIUS                 1023
#define IDC_HELIOCENTRIC_SPHERICAL      1024
#define IDC_SATURN_RADIUS               1025
#define IDC_URANUS_RADIUS               1026
#define IDC_NEPTUNE_RADIUS              1027
#define IDC_PLUTO_RADIUS                1028
#define IDC_EARTH_LAMBDA                1029
#define IDC_EARTH_BETA                  1030
#define IDC_EARTH_RADIUS                1031
#define IDC_MERCURY_LAMBDA              1032
#define IDC_VENUS_LAMBDA                1033
#define IDC_MARS_LAMBDA                 1034
#define IDC_JUPITER_LAMBDA              1035
#define IDC_SATURN_LAMBDA               1036
#define IDC_URANUS_LAMBDA               1037
#define IDC_NEPTUNE_LAMBDA              1038
#define IDC_PLUTO_LAMBDA                1039
#define IDC_MERCURY_BETA                1040
#define IDC_VENUS_BETA                  1041
#define IDC_MARS_BETA                   1042
#define IDC_JUPITER_BETA                1043
#define IDC_SATURN_BETA                 1044
#define IDC_URANUS_BETA                 1045
#define IDC_NEPTUNE_BETA                1046
#define IDC_PLUTO_BETA                  1047
#define IDC_RADIUS_DISPLAY_TIME         1048
#define IDC_RADIUS_DISPLAY_LAMBDA2      1049
#define IDC_RADIUS_DISPLAY_BETA2        1050
#define IDC_RADIUS_DISPLAY_RADIUS1      1051
#define IDC_DO_ALL                      1052
#define IDC_DO_SUN                      1053
#define IDC_DO_MOON                     1054
#define IDC_DO_MERCURY                  1055
#define IDC_DO_VENUS                    1056
#define IDC_DO_EARTH                    1057
#define IDC_DO_MARS                     1058
#define IDC_DO_JUPITER                  1059
#define IDC_DO_SATURN                   1060
#define IDC_DO_URANUS                   1061
#define IDC_DO_NEPTUNE                  1062
#define IDC_DO_PLUTO                    1063
#define IDC_SUN_AZIMUTH                 1064
#define IDC_HELIOCENTRIC_CARTESIAN      1065
#define IDC_GEOCENTRIC_CARTESIAN        1066
#define IDC_GEOCENTRIC_SPHERICAL_TRUE   1067
#define IDC_GEOCENTRIC_SPHERICAL_APP    1068
#define IDC_EQUATORIAL_APPARENT         1069
#define IDC_RADIUS_DISPLAY_LAMBDA1      1070
#define IDC_RADIUS_DISPLAY_BETA1        1071
#define IDC_RADIUS_DISPLAY_RADIUS2      1072
#define IDC_DISPLAY_TITLE               1073
#define IDC_RADIUS_DISPLAY_HORIZON      1074
#define IDC_DEGREE_STYLE                1075
#define IDC_A_DEGREE_STYLE              1076
#define IDC_POSITION_TITLE              1077
#define IDC_NOW                         1078
#define IDC_SUN_ALTITUDE                1079
#define IDC_JULIAN_DATE                 1080
#define IDC_RISE_SET_TRANSIT            1081
#define IDC_ASTRONOMICAL_DATA           1082
#define IDC_JULIAN_DAY2                 1083
#define IDC_JULIAN_DAY_EPHEMERIS        1084
#define IDC_DELTA_T                     1085
#define IDC_MEAN_SIDEREAL_DEG           1086
#define IDC_APP_SIDEREAL_DEG            1087
#define IDC_ECCENTRICITY                1088
#define IDC_LONGITUDE_PERIHELION        1089
#define IDC_MEAN_ANOMALY                1090
#define IDC_MEAN_OBLIQUITY_ECLIPTIC     1091
#define IDC_TRUE_OBLIQUITY_ECLIPTIC     1092
#define IDC_MOON_AZIMUTH                1093
#define IDC_MOON_ALTITUDE               1094
#define IDC_LOCAL_TIME                  1095
#define IDC_UT                          1096
#define IDC_MERCURY_AZIMUTH             1097
#define IDC_DATA_DISPLAY_LAT            1098
#define IDC_LAT                         1099
#define IDC_BUTTON_DST                  1100
#define IDC_BUTTON_NS                   1101
#define IDC_BUTTON_WE                   1102
#define IDC_BUTTON_AMPM                 1103
#define IDC_MERCURY_ALTITUDE            1104
#define IDC_VENUS_AZIMUTH               1105
#define IDC_VENUS_ALTITUDE              1106
#define IDC_MARS_AZIMUTH                1107
#define IDC_MARS_ALTITUDE               1108
#define IDC_RADIO_DECIMAL               1109
#define IDC_RADIO_HMS                   1110
#define IDC_RADIO_RADIAN                1111
#define IDC_OUTPUT_GROUP                1112
#define IDC_JUPITER_AZIMUTH             1113
#define IDC_MERCURY_RETROGRADE          1114
#define IDC_VENUS_RETROGRADE            1115
#define IDC_MARS_RETROGRADE             1116
#define IDC_JUPITER_RETROGRADE          1117
#define IDC_SATURN_RETROGRADE           1118
#define IDC_URANUS_RETROGRADE           1119
#define IDC_NEPTUNE_RETROGRADE          1120
#define IDC_PLUTO_RETROGRADE            1121
#define IDC_SHOW                        1122
#define IDC_ES_YEAR                     1123
#define IDC_VER_EQUI                    1124
#define IDC_SUM_SOL                     1125
#define IDC_AUT_EQUI                    1126
#define IDC_WIN_SOL                     1127
#define IDC_RUN                         1128
#define IDC_VE_DUR                      1129
#define IDC_SS_DUR                      1130
#define IDC_AE_DUR                      1131
#define IDC_WS_DUR                      1132
#define IDC_GHA_DEC                     1133
#define IDC_SPIN_YEAR                   1134
#define IDC_SPIN_DATE                   1135
#define IDC_SPIN_MONTH                  1136
#define IDC_SPIN_PRECISION              1137
#define IDC_SPIN_TIME_ZONE              1138
#define IDC_ASC_NODE_POS                1139
#define IDC_VENUS_RADIUS                1140
#define IDC_ASC_NODE_SIGN               1141
#define IDC_SUN_HOUSE                   1142
#define IDC_ALL                         1143
#define IDC_ARIES                       1144
#define IDC_VENUS                       1145
#define IDC_MARS                        1146
#define IDC_JUPITER                     1147
#define IDC_SATURN                      1148
#define IDC_SUN                         1149
#define IDC_MOON                        1150
#define IDC_JUPITER_RADIUS              1151
#define IDC_YEAR_IN                     1152
#define IDC_MONTH_IN                    1153
#define IDC_DAY_IN                      1154
#define IDC_HOUR_IN                     1155
#define IDC_YEAR_OUT                    1156
#define IDC_MONTH_OUT                   1157
#define IDC_DAY_OUT                     1158
#define IDC_HOUR_OUT                    1159
#define IDC_YEAR_INC                    1160
#define IDC_MONTH_INC                   1161
#define IDC_DAY_INC                     1162
#define IDC_HOUR_INC                    1163
#define IDC_MINUTE_INC                  1164
#define IDC_SECOND_INC                  1165
#define IDC_NO_RUNS                     1166
#define IDC_MOON_HOUSE                  1167
#define IDC_PRECISION                   1168
#define IDC_MERCURY_HOUSE               1169
#define IDC_PROGRESS                    1170
#define IDC_VENUS_HOUSE                 1171
#define IDC_MARS_HOUSE                  1172
#define IDC_HMS_IN                      1173
#define IDC_HMS_OUT                     1174
#define IDC_TYPE                        1175
#define IDC_DO                          1176
#define IDC_VALUE                       1177
#define IDC_DATA_DISPLAY_LON            1178
#define IDC_LON                         1179
#define IDC_SUN_DUR                     1180
#define IDC_MOON_DUR                    1181
#define IDC_MERCURY_DUR                 1182
#define IDC_VENUS_DUR                   1183
#define IDC_MARS_DUR                    1184
#define IDC_JUPITER_DUR                 1185
#define IDC_SATURN_DUR                  1186
#define IDC_URANUS_DUR                  1187
#define IDC_NEPTUNE_DUR                 1188
#define IDC_PLUTO_DUR                   1189
#define IDC_KEEP_VALUES                 1190
#define IDC_JUPITER_HOUSE               1191
#define IDC_SATURN_HOUSE                1192
#define IDC_URANUS_HOUSE                1193
#define IDC_NEPTUNE_HOUSE               1194
#define IDC_PLUTO_HOUSE                 1195
#define IDC_ASC_NODE_HOUSE              1196
#define IDC_MOON_LAMBDA                 1197
#define IDC_BODY1                       1198
#define IDC_MOON_BETA                   1199
#define IDC_ANGULAR_SEPARATION          1200
#define IDC_BODY2                       1201
#define IDC_ANG_SEP                     1202
#define IDC_SUN_LAMBDA                  1203
#define IDC_SUN_BETA                    1204
#define IDC_CENTRIC                     1205
#define IDC_MOON_RADIUS                 1206
#define IDC_SUN_RADIUS                  1207
#define IDC_GEOCENTRIC                  1208
#define IDC_HELIOCENTRIC                1209
#define IDC_HOR                         1210
#define IDC_DD_SHOW                     1211
#define IDC_NAME                        1212
#define IDC_RADIUS_DISPLAY_ABOVE        1213
#define IDC_BIRTH_PLACE                 1214
#define IDC_BIRTH_TIME                  1215
#define IDC_SUN_POS                     1216
#define IDC_MOON_POS                    1217
#define IDC_MERCURY_POS                 1218
#define IDC_VENUS_POS                   1219
#define IDC_MARS_POS                    1220
#define IDC_JUPITER_POS                 1221
#define IDC_SATURN_POS                  1222
#define IDC_URANUS_POS                  1223
#define IDC_NEPTUNE_POS                 1224
#define IDC_PLUTO_POS                   1225
#define IDC_SUN_SIGN                    1226
#define IDC_MOON_SIGN                   1227
#define IDC_MERCURY_SIGN                1228
#define IDC_VENUS_SIGN                  1229
#define IDC_MARS_SIGN                   1230
#define IDC_JUPITER_SIGN                1231
#define IDC_SATURN_SIGN                 1232
#define IDC_URANUS_SIGN                 1233
#define IDC_NEPTUNE_SIGN                1234
#define IDC_PLUTO_SIGN                  1235
#define IDC_MERC_RETROGRADE             1236
#define IDC_VEN_RETROGRADE              1237
#define IDC_MAR_RETROGRADE              1238
#define IDC_JUP_RETROGRADE              1239
#define IDC_SAT_RETROGRADE              1240
#define IDC_URAN_RETROGRADE             1241
#define IDC_NEP_RETROGRADE              1242
#define IDC_PLUT_RETROGRADE             1243
#define IDC_MOON_QUARTER                1244
#define IDC_MOON_QUART                  1245
#define IDC_SUN_RISE                    1246
#define IDC_SUN_TRANSIT                 1247
#define IDC_SUN_SET                     1248
#define IDC_SUN_2                       1249
#define IDC_RTS_DATE                    1250
#define IDC_RTS_LAT                     1251
#define IDC_RTS_LONG                    1252
#define IDC_MOON_RISE                   1253
#define IDC_MOON_TRANSIT                1254
#define IDC_MOON_SET                    1255
#define IDC_MOON_2                      1256
#define IDC_SUN_UP                      1257
#define IDC_MOON_UP                     1258
#define IDC_MERCURY_UP                  1259
#define IDC_VENUS_UP                    1260
#define IDC_MERCURY_RISE                1261
#define IDC_MERCURY_TRANSIT             1262
#define IDC_MERCURY_SET                 1263
#define IDC_MERCURY_2                   1264
#define IDC_VENUS_RISE                  1265
#define IDC_VENUS_TRANSIT               1266
#define IDC_VENUS_SET                   1267
#define IDC_VENUS_2                     1268
#define IDC_MARS_RISE                   1269
#define IDC_MARS_TRANSIT                1270
#define IDC_MARS_SET                    1271
#define IDC_MARS_2                      1272
#define IDC_MARS_UP                     1273
#define IDC_JUPITER_UP                  1274
#define IDC_SATURN_UP                   1275
#define IDC_URANUS_UP                   1276
#define IDC_JUPITER_RISE                1277
#define IDC_JUPITER_TRANSIT             1278
#define IDC_JUPITER_SET                 1279
#define IDC_JUPITER_2                   1280
#define IDC_SATURN_RISE                 1281
#define IDC_SATURN_TRANSIT              1282
#define IDC_SATURN_SET                  1283
#define IDC_SATURN_2                    1284
#define IDC_URANUS_RISE                 1285
#define IDC_URANUS_TRANSIT              1286
#define IDC_URANUS_SET                  1287
#define IDC_URANUS_2                    1288
#define IDC_NEPTUNE_RISE                1289
#define IDC_NEPTUNE_TRANSIT             1290
#define IDC_NEPTUNE_SET                 1291
#define IDC_NEPTUNE_2                   1292
#define IDC_PLUTO_RISE                  1293
#define IDC_PLUTO_TRANSIT               1294
#define IDC_PLUTO_SET                   1295
#define IDC_PLUTO_2                     1296
#define IDC_NEPTUNE_UP                  1297
#define IDC_PLUTO_UP                    1298
#define IDC_TIME_STYLE                  1299
#define IDC_SPIN_OPT_PRECISION          1300
#define IDC_ALMANAC                     1301
#define IDC_MERCURY                     1302
#define IDC_EARTH                       1303
#define IDC_URANUS                      1304
#define IDC_NEPTUNE                     1305
#define IDC_PLUTO                       1306
#define IDC_ALMANAC_LIST                1307
#define IDC_LAT_START                   1308
#define IDC_LAT_START_NS                1309
#define IDC_LON_START                   1310
#define IDC_LON_START_EW                1311
#define IDC_LAT_END                     1312
#define IDC_LAT_END_NS                  1313
#define IDC_LON_END                     1314
#define IDC_LON_END_EW                  1315
#define IDC_LAT_INC                     1316
#define IDC_LON_INC                     1317
#define IDC_LAT_RUNS                    1318
#define IDC_ALM_TIME_ZONE               1319
#define IDC_LON_RUNS                    1320
#define IDC_DECIMAL_RADIO               1321
#define IDC_DEGREE_RADIO                1322
#define IDC_RADIAN_RADIO                1323
#define IDC_ALM_OUTPUT                  1324
#define IDC_LOCATION                    1325
#define IDC_PLACE_ADD                   1329
#define IDC_PLACE_DELETE                1330
#define IDC_GEO                         1331
#define IDC_HELIO                       1332
#define IDC_ANG_SEP_GROUP               1333
#define IDC_MAGNITUDE                   1336
#define IDC_VMAG                        1337
#define IDC_CONSTELLATION               1338
#define IDC_CONST_LIST                  1339
#define IDC_STAR_NAMES                  1340
#define IDC_CONST_NAMES                 1341
#define IDC_STARS                       1342
#define IDC_STAR_TO_FILE                1343
#define IDC_STAR_FILENAME               1344
#define IDC_MAGNETIC_VARIATION          1347
#define IDC_VARIATION                   1348
#define IDC_DIP                         1350
#define IDC_VAR_LOCATION                1351
#define IDC_VAR_LAT                     1352
#define IDC_VAR_LON                     1353
#define IDC_VAR_TIME                    1354
#define IDC_VAR_DEGREE_STYLE            1355
#define IDC_PLANETS1                    1357
#define IDC_STARS1                      1358
#define IDC_MOON_YEAR                   1365
#define IDC_MOON_MONTH                  1366
#define IDC_MOON_DAY                    1367
#define IDC_MOON_HOUR                   1368
#define IDC_MOON_AMPM                   1369
#define IDC_MOON_DST                    1370
#define IDC_NEXT_QUARTER                1371
#define IDC_NEXT_NEW                    1372
#define IDC_NEXT_FULL                   1373
#define IDC_NEXT_QUARTER_BTN            1374
#define IDC_NEXT_NEW_BTN                1375
#define IDC_NEXT_FULL_BTN               1376
#define IDC_MOON_PHASE_BTN              1377
#define IDC_PREVIOUS_QTR_BTN            1378
#define IDC_PREVIOUS_QUARTER            1379
#define IDC_PREV_QTR                    1380
#define IDC_NEXT_QTR                    1381
#define IDC_MOON_PHASE_ALL              1382
#define IDC_MOON_PHASE_CLEAR            1383
#define IDC_UT_BTN                      1384
#define IDC_MOON_DO_YEAR                1385
#define IDC_TIME_TYPE                   1386
#define IDC_STAR_VIEW_DIR               1387
#define IDC_MAG_VALUE                   1390
#define IDC_SHOW_CONS                   1391
#define IDC_SHOW_STARS                  1392
#define IDC_SHOW_STAR_NAMES             1393
#define IDC_SHOW_CON_NAMES              1394
#define IDC_VIEW_DIR                    1395
#define IDC_MAG_SLIDER                  1398
#define IDC_ERR_MESSAGE                 1400
#define IDC_WORKING                     1403
#define IDC_MAGNETIC_HORIZONTAL         1404
#define IDC_MAGNETIC_NORTH              1405
#define IDC_MAGNETIC_EAST               1406
#define IDC_MAGNETIC_VERTICAL           1407
#define IDC_MAGNETIC_TOTAL              1408
#define IDC_STARS_PRINT                 1409
#define IDC_BUTTON2                     1410
#define IDC_NATAL_PRINT                 1410
#define ID_TOOLS_PLANETS                32772
#define ID_OPTIONS                      32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1411
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
